@startuml
title UC2: Search Recipes - Activity Diagram

start

:Input user query;

if (search by?) then (Dish Name)
  :Search by exact name or titles that include it;
  :Click 'submit' button;
  :Search in recipe database by dish name;
else (Ingredient)
  :Type the ingredient;
  :Click 'submit' button;
  if (ingredient exists in database?) then (yes)
    :Search in recipe database by ingredient;
  else (no)
    :Display error: Ingredient not found;
    stop
  endif
endif

:Display search results;

if (want more personalized search?) then (yes)
  :Display filter menu;
  :Click on the desired filters;
  :Apply filters;
  :Display filtered results;
else (no)
endif

stop

@enduml
