@startuml
title UC2: Search Recipes - Activity Diagram

start

:Input user query;
:Choose search type;

partition "Query Type Selection" {
	if (search by?) then (Dish Name)
    	:Type the dish name;
    	while (name exists in database?) is (no)
        	:Display error: Dish name not found;
        	:Type the dish name;
    	endwhile
    	:Search in recipe database by dish name;
	else (Ingredient)
    	:Type the ingredient;
    	while (ingredient exists in database?) is (no)
        	:Display error: Ingredient not found;
        	:Type the ingredient;
    	endwhile
    	:Search in recipe database by ingredient;
	endif
}

partition "Search Results Display" {
	:Display search results;
	if (want more specific search?) then (yes)
    	:Display filter options;
    	note
    	Possible options: Cooking time, difficulty, diet, etc.
    	end note
    	:Select and apply filters;
    	:Display filtered results;
	else (no)
    	stop
	endif
}

stop

@enduml

